# Generated by Django 5.2.8 on 2025-12-11 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('keywords', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'blogs',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop_title', models.CharField(max_length=255)),
                ('prop_des', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
                ('purpose', models.IntegerField(blank=True, null=True)),
                ('prop_price', models.CharField(max_length=50)),
                ('prop_beds', models.IntegerField(blank=True, null=True)),
                ('prop_baths', models.IntegerField(blank=True, null=True)),
                ('prop_size', models.CharField(max_length=50)),
                ('prop_year_built', models.CharField(blank=True, max_length=10, null=True)),
                ('prop_features', models.JSONField(blank=True, default=list)),
                ('property_map_address', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('administrative_area_level_1', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('lat', models.CharField(blank=True, max_length=100)),
                ('lng', models.CharField(blank=True, max_length=100)),
                ('prop_google_street_view', models.CharField(default='hide', max_length=10)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('featured', models.BooleanField(default=False)),
                ('login_required', models.BooleanField(default=False)),
                ('disclaimer', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Property',
            },
        ),
    ]
