# Generated by Django 5.2.8 on 2025-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
