# Generated by Django 5.2.8 on 2025-12-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_property_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
