# Generated by Django 5.2.8 on 2025-12-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_property_category_alter_property_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(default='approved', max_length=20),
        ),
    ]
