# Generated by Django 5.2.8 on 2025-12-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_applying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
