# Generated by Django 5.2.8 on 2025-12-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_applying_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='license_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
