# Generated by Django 5.2.8 on 2025-12-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_applying_license_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applying',
            name='ssn',
            field=models.CharField(max_length=100),
        ),
    ]
