# Generated by Django 5.2.8 on 2025-12-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_booking_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
