# Generated by Django 5.2.8 on 2025-12-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_property_video_file_property_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_image',
            field=models.IntegerField(default=0, help_text='Index of featured image in gallery_images'),
        ),
    ]
